version: '3.7'

services: 
    nginx:
        image: nginx:1.15
        container_name: nginx
        volumes: 
            - ./:/var/www
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - 8002:8000
        networks: 
            - my-networks
        depends_on: 
            - fastapi
    fastapi:
            build: 
                context: ./
                dockerfile: DockerFile
            container_name: fastapi
            command: uvicorn app.server:app --reload --workers 1 --host 127.0.0.1 --port 8000
            volumes: 
                - ./:/var/www
            networks: 
                my-networks:
                    aliases: 
                        - fastapi-app
networks: 
    my-networks:

